# Generated by Django 6.0 on 2025-12-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_days',
            field=models.PositiveIntegerField(default=3, verbose_name='Yetkazib berish muddati (kun)'),
        ),
    ]
