# Generated by Django 6.0 on 2025-12-22 06:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_delivery_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price_zum',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_zum',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Umumiy narx (USD)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Narxi (USD)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sotib olingan vaqt'),
        ),
    ]
