# Generated by Django 6.0 on 2025-12-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_order_total_price_zum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Buyurtma qabul qilindi'), ('shipping', 'Yetkazilmoqda'), ('delivered', 'Yetkazib berildi')], default='accepted', max_length=20, verbose_name='Buyurtma holati'),
        ),
    ]
